[global]
method = "island"
epoch_length = 100
max_generations = 1000
population_size = 100
migration_rate = 0.1

[[island]]
dst_island = 1
mutation_rate = 0.01
max_mutation_strength = 0.05

[[island]]
src_island = 0
dst_island = 2
mutation_rate = 0.01
max_mutation_strength = 0.05

[[island]]
src_island = 1
mutation_rate = 0.01
max_mutation_strength = 0.05
