[global]
method = "island"
epoch_length = 200
n_epochs = 10
population_size = 500
migration_rate = 0.5

[[island]]
src_islands = [2]
dst_islands = [1]
mutation_rate = 0.01
max_mutation_strength = 0.01

[[island]]
src_islands = [0]
dst_islands = [2]
mutation_rate = 0.05
max_mutation_strength = 0.1

[[island]]
src_islands = [1]
dst_islands = [0]
mutation_rate = 0.5
max_mutation_strength = 0.2
